# File: azure-pipelines.yml

stages:

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
    
- template: templates/publish.yml
  parameters:
    buildConfiguration: 'Release'
